<?php

return [
    // ── Umum ──────────────────────────────────────────────────────────────
    [
        'key' => 'general',
        'name' => 'Umum',
        'info' => 'Informasi toko, branding, promo, SEO, dan integrasi.',
        'sort' => 1,
    ],
    [
        'key' => 'general.store',
        'name' => 'Info Toko',
        'info' => 'Nama brand, lokasi, dan kontak WhatsApp.',
        'sort' => 1,
        'fields' => [
            ['name' => 'brand_name', 'title' => 'Nama Brand', 'type' => 'text', 'validation' => 'nullable|string|max:255'],
            ['name' => 'store_location', 'title' => 'Lokasi Toko', 'type' => 'text', 'validation' => 'nullable|string|max:255'],
            ['name' => 'wa_number', 'title' => 'Nomor WhatsApp', 'type' => 'text', 'validation' => 'nullable|string|max:20'],
        ],
    ],
    [
        'key' => 'general.design',
        'name' => 'Desain & Branding',
        'info' => 'Logo, favicon, warna tema, dan sosial media.',
        'sort' => 2,
        'fields' => [
            ['name' => 'brand_logo', 'title' => 'Logo', 'type' => 'image', 'disk' => 'public', 'path' => 'logos', 'validation' => 'nullable|image|mimes:png,jpg,jpeg,webp|max:2048'],
            ['name' => 'favicon', 'title' => 'Favicon', 'type' => 'image', 'disk' => 'public', 'path' => 'favicons', 'validation' => 'nullable|image|mimes:png,jpg,jpeg,webp,ico|max:512'],
            ['name' => 'color_gold', 'title' => 'Warna Emas', 'type' => 'color', 'default' => '#C2A56D', 'validation' => 'nullable|string|max:7'],
            ['name' => 'color_accent', 'title' => 'Warna Aksen', 'type' => 'color', 'default' => '#547A95', 'validation' => 'nullable|string|max:7'],
            ['name' => 'social_instagram', 'title' => 'Instagram', 'type' => 'text', 'validation' => 'nullable|string|max:255'],
            ['name' => 'social_facebook', 'title' => 'Facebook', 'type' => 'text', 'validation' => 'nullable|string|max:255'],
            ['name' => 'social_tiktok', 'title' => 'TikTok', 'type' => 'text', 'validation' => 'nullable|string|max:255'],
        ],
    ],
    [
        'key' => 'general.header_offer',
        'name' => 'Bar Promo',
        'info' => 'Strip promo di bagian atas situs.',
        'sort' => 3,
        'fields' => [
            ['name' => 'promo_bar_enabled', 'title' => 'Aktifkan Bar Promo', 'type' => 'boolean', 'default' => '1'],
            ['name' => 'promo_bar_text', 'title' => 'Teks Promo', 'type' => 'text', 'validation' => 'nullable|string|max:255'],
            ['name' => 'promo_bar_cta_label', 'title' => 'Label CTA', 'type' => 'text', 'default' => 'Hubungi WA', 'validation' => 'nullable|string|max:100'],
            ['name' => 'promo_bar_bg_color', 'title' => 'Warna Latar', 'type' => 'color', 'validation' => 'nullable|string|max:7'],
            ['name' => 'promo_bar_text_color', 'title' => 'Warna Teks', 'type' => 'color', 'validation' => 'nullable|string|max:7'],
        ],
    ],
    [
        'key' => 'general.seo',
        'name' => 'SEO',
        'info' => 'Meta title, deskripsi, keywords, gambar Open Graph, dan sitemap.',
        'sort' => 4,
        'fields' => [
            ['name' => 'site_title', 'title' => 'Judul Situs', 'type' => 'text', 'validation' => 'nullable|string|max:255'],
            ['name' => 'site_description', 'title' => 'Deskripsi Situs', 'type' => 'textarea', 'validation' => 'nullable|string|max:500'],
            ['name' => 'site_keywords', 'title' => 'Keywords', 'type' => 'text', 'validation' => 'nullable|string|max:500'],
            ['name' => 'og_image', 'title' => 'Gambar Open Graph', 'type' => 'image', 'disk' => 'public', 'path' => 'seo', 'validation' => 'nullable|image|mimes:jpeg,png,jpg,webp|max:2048'],
            ['name' => 'sitemap_enabled', 'title' => 'Aktifkan Sitemap', 'type' => 'boolean', 'default' => '1'],
            ['name' => 'sitemap_include_products', 'title' => 'Sitemap: Produk', 'type' => 'boolean', 'default' => '1', 'depends' => 'sitemap_enabled:1'],
            ['name' => 'sitemap_include_categories', 'title' => 'Sitemap: Kategori', 'type' => 'boolean', 'default' => '1', 'depends' => 'sitemap_enabled:1'],
            ['name' => 'sitemap_include_cms', 'title' => 'Sitemap: Halaman CMS', 'type' => 'boolean', 'default' => '1', 'depends' => 'sitemap_enabled:1'],
        ],
    ],
    [
        'key' => 'general.email',
        'name' => 'Email & Notifikasi',
        'info' => 'Konfigurasi SMTP untuk email pesanan dan notifikasi.',
        'sort' => 6,
        'fields' => [
            ['name' => 'mail_enabled', 'title' => 'Gunakan Pengaturan SMTP Admin', 'type' => 'boolean', 'default' => '0'],
            [
                'name' => 'mail_mailer',
                'title' => 'Mailer',
                'type' => 'select',
                'default' => 'smtp',
                'options' => [
                    ['title' => 'SMTP', 'value' => 'smtp'],
                    ['title' => 'Log (Development)', 'value' => 'log'],
                ],
                'depends' => 'mail_enabled:1',
            ],
            ['name' => 'mail_host', 'title' => 'SMTP Host', 'type' => 'text', 'validation' => 'nullable|string|max:255', 'depends' => 'mail_enabled:1'],
            ['name' => 'mail_port', 'title' => 'SMTP Port', 'type' => 'number', 'default' => '587', 'validation' => 'nullable|integer|min:1|max:65535', 'depends' => 'mail_enabled:1'],
            ['name' => 'mail_username', 'title' => 'SMTP Username', 'type' => 'text', 'validation' => 'nullable|string|max:255', 'depends' => 'mail_enabled:1'],
            ['name' => 'mail_password', 'title' => 'SMTP Password', 'type' => 'password', 'validation' => 'nullable|string|max:255', 'depends' => 'mail_enabled:1'],
            [
                'name' => 'mail_encryption',
                'title' => 'Enkripsi',
                'type' => 'select',
                'default' => 'tls',
                'options' => [
                    ['title' => 'TLS', 'value' => 'tls'],
                    ['title' => 'SSL', 'value' => 'ssl'],
                    ['title' => 'Tidak ada', 'value' => ''],
                ],
                'depends' => 'mail_enabled:1',
            ],
            ['name' => 'mail_from_address', 'title' => 'From Address', 'type' => 'text', 'validation' => 'nullable|email|max:255', 'depends' => 'mail_enabled:1'],
            ['name' => 'mail_from_name', 'title' => 'From Name', 'type' => 'text', 'validation' => 'nullable|string|max:255', 'depends' => 'mail_enabled:1'],
        ],
    ],
    [
        'key' => 'general.gdpr',
        'name' => 'Cookie & GDPR',
        'info' => 'Banner persetujuan cookie untuk pengunjung.',
        'sort' => 7,
        'fields' => [
            ['name' => 'gdpr_enabled', 'title' => 'Aktifkan Banner Cookie', 'type' => 'boolean', 'default' => '0'],
            ['name' => 'gdpr_message', 'title' => 'Pesan Cookie', 'type' => 'textarea', 'default' => 'Situs ini menggunakan cookie untuk meningkatkan pengalaman Anda.', 'validation' => 'nullable|string|max:1000', 'depends' => 'gdpr_enabled:1'],
            ['name' => 'gdpr_policy_url', 'title' => 'URL Kebijakan Privasi', 'type' => 'text', 'validation' => 'nullable|string|max:255', 'depends' => 'gdpr_enabled:1'],
            ['name' => 'gdpr_cookie_lifetime_days', 'title' => 'Masa Berlaku Consent (hari)', 'type' => 'number', 'default' => '365', 'validation' => 'nullable|integer|min:1|max:3650', 'depends' => 'gdpr_enabled:1'],
        ],
    ],
    [
        'key' => 'general.tracking',
        'name' => 'Tracking & Script',
        'info' => 'Meta Pixel, Google Tag Manager, dan script kustom.',
        'sort' => 5,
        'fields' => [
            ['name' => 'meta_pixel_id', 'title' => 'Meta Pixel ID', 'type' => 'text', 'validation' => 'nullable|string|max:50|regex:/^[0-9]*$/'],
            ['name' => 'google_tag_manager_id', 'title' => 'Google Tag Manager ID', 'type' => 'text', 'validation' => 'nullable|string|max:50|regex:/^[A-Za-z0-9-]*$/'],
            ['name' => 'custom_head_scripts', 'title' => 'Script Head', 'type' => 'textarea', 'validation' => 'nullable|string|max:10000'],
            ['name' => 'custom_body_scripts', 'title' => 'Script Body', 'type' => 'textarea', 'validation' => 'nullable|string|max:10000'],
        ],
    ],

    // ── Katalog ───────────────────────────────────────────────────────────
    [
        'key' => 'catalog',
        'name' => 'Katalog',
        'info' => 'Pengaturan produk, stok, dan ulasan.',
        'sort' => 2,
    ],
    [
        'key' => 'catalog.products',
        'name' => 'Produk & Stok',
        'info' => 'Ambang stok rendah, tampilan habis, dan satuan berat.',
        'sort' => 1,
        'fields' => [
            ['name' => 'low_stock_threshold', 'title' => 'Ambang Stok Rendah', 'type' => 'number', 'default' => '5', 'validation' => 'nullable|integer|min:0'],
            [
                'name' => 'out_of_stock_behavior',
                'title' => 'Produk Habis Stok',
                'type' => 'select',
                'default' => 'show_label',
                'options' => [
                    ['title' => 'Tampilkan label "Habis"', 'value' => 'show_label'],
                    ['title' => 'Sembunyikan dari katalog', 'value' => 'hide'],
                    ['title' => 'Izinkan backorder (global default)', 'value' => 'allow_backorder'],
                ],
            ],
            [
                'name' => 'weight_unit',
                'title' => 'Satuan Berat',
                'type' => 'select',
                'default' => 'gram',
                'options' => [
                    ['title' => 'Gram', 'value' => 'gram'],
                    ['title' => 'Kilogram', 'value' => 'kg'],
                    ['title' => 'Pound', 'value' => 'lb'],
                ],
            ],
        ],
    ],
    [
        'key' => 'catalog.reviews',
        'name' => 'Ulasan',
        'info' => 'Moderasi dan persyaratan ulasan produk.',
        'sort' => 2,
        'fields' => [
            ['name' => 'auto_approve_reviews', 'title' => 'Auto-approve Ulasan', 'type' => 'boolean', 'default' => '0'],
            ['name' => 'reviews_require_login', 'title' => 'Wajib Login untuk Ulasan', 'type' => 'boolean', 'default' => '0'],
        ],
    ],

    // ── Penjualan ─────────────────────────────────────────────────────────
    [
        'key' => 'sales',
        'name' => 'Penjualan',
        'info' => 'Pajak, ongkir, checkout, dan pesanan.',
        'sort' => 3,
    ],
    [
        'key' => 'sales.taxes.calculation',
        'name' => 'Perhitungan Pajak',
        'info' => 'Cara pajak dihitung dan ditampilkan.',
        'sort' => 1,
        'fields' => [
            ['name' => 'tax_included', 'title' => 'Harga Sudah Termasuk Pajak', 'type' => 'boolean', 'default' => '0'],
        ],
    ],
    [
        'key' => 'sales.taxes.rates',
        'name' => 'Tarif Pajak',
        'info' => 'Kelola tarif pajak per kategori produk.',
        'sort' => 2,
        'type' => 'link',
        'href' => '/admin/tax-rates',
    ],
    [
        'key' => 'sales.taxes.zones',
        'name' => 'Zona Pajak',
        'info' => 'Petakan provinsi/kota ke tarif pajak.',
        'sort' => 3,
        'type' => 'link',
        'href' => '/admin/tax-zones',
    ],
    [
        'key' => 'sales.shipping',
        'name' => 'Ongkir',
        'info' => 'Kelola tarif ongkir per kota.',
        'sort' => 4,
        'type' => 'link',
        'href' => '/admin/shipping-costs',
    ],
    [
        'key' => 'sales.checkout',
        'name' => 'Checkout',
        'info' => 'Minimum order dan guest checkout.',
        'sort' => 5,
        'fields' => [
            ['name' => 'guest_checkout_enabled', 'title' => 'Izinkan Guest Checkout', 'type' => 'boolean', 'default' => '1'],
            ['name' => 'minimum_order_enabled', 'title' => 'Aktifkan Minimum Order', 'type' => 'boolean', 'default' => '0'],
            ['name' => 'minimum_order_amount', 'title' => 'Minimum Order (Rp)', 'type' => 'number', 'default' => '0', 'validation' => 'nullable|integer|min:0', 'depends' => 'minimum_order_enabled:1'],
            ['name' => 'minimum_order_message', 'title' => 'Pesan Minimum Order', 'type' => 'text', 'default' => 'Minimum pembelian belum terpenuhi.', 'validation' => 'nullable|string|max:255', 'depends' => 'minimum_order_enabled:1'],
            ['name' => 'unique_payment_amount_enabled', 'title' => 'Nominal Transfer Unik', 'type' => 'boolean', 'default' => '1'],
            ['name' => 'newsletter_opt_in_enabled', 'title' => 'Checkbox Newsletter di Checkout', 'type' => 'boolean', 'default' => '0'],
            ['name' => 'newsletter_opt_in_label', 'title' => 'Label Newsletter', 'type' => 'text', 'default' => 'Berlangganan newsletter untuk promo & update', 'validation' => 'nullable|string|max:255', 'depends' => 'newsletter_opt_in_enabled:1'],
        ],
    ],
    [
        'key' => 'sales.order_creation',
        'name' => 'Pembuatan Pesanan',
        'info' => 'Format nomor pesanan dan batas retry.',
        'sort' => 6,
        'fields' => [
            [
                'name' => 'order_number_mode',
                'title' => 'Mode Nomor Pesanan',
                'type' => 'select',
                'default' => 'random',
                'options' => [
                    ['title' => 'Acak (Random)', 'value' => 'random'],
                    ['title' => 'Berurut (Sequential)', 'value' => 'sequential'],
                ],
            ],
            ['name' => 'order_number_prefix', 'title' => 'Prefix Nomor Pesanan', 'type' => 'text', 'default' => 'INV-', 'validation' => 'nullable|string|max:20'],
            ['name' => 'order_number_length', 'title' => 'Panjang Nomor', 'type' => 'number', 'default' => '8', 'validation' => 'nullable|integer|min:4|max:16'],
            ['name' => 'order_number_suffix', 'title' => 'Suffix Nomor Pesanan', 'type' => 'text', 'default' => '', 'validation' => 'nullable|string|max:20'],
            ['name' => 'order_number_start', 'title' => 'Nomor Awal (Sequential)', 'type' => 'number', 'default' => '1', 'validation' => 'nullable|integer|min:1', 'depends' => 'order_number_mode:sequential'],
            ['name' => 'max_checkout_retry_attempts', 'title' => 'Max Retry Checkout', 'type' => 'number', 'default' => '3', 'validation' => 'nullable|integer|min:1|max:10'],
        ],
    ],
    [
        'key' => 'sales.invoice',
        'name' => 'Faktur',
        'info' => 'Header, footer, dan tampilan faktur pesanan.',
        'sort' => 7,
        'fields' => [
            ['name' => 'invoice_company_name', 'title' => 'Nama Perusahaan', 'type' => 'text', 'validation' => 'nullable|string|max:255'],
            ['name' => 'invoice_address', 'title' => 'Alamat Perusahaan', 'type' => 'textarea', 'validation' => 'nullable|string|max:500'],
            ['name' => 'invoice_footer_text', 'title' => 'Teks Footer Faktur', 'type' => 'textarea', 'validation' => 'nullable|string|max:500'],
            ['name' => 'invoice_show_tax_breakdown', 'title' => 'Tampilkan Rincian Pajak', 'type' => 'boolean', 'default' => '0'],
        ],
    ],
    [
        'key' => 'sales.rma',
        'name' => 'Kebijakan Retur',
        'info' => 'Atur kebijakan retur global.',
        'sort' => 8,
        'type' => 'link',
        'href' => '/admin/returns/policy',
    ],

    // ── Pembayaran ────────────────────────────────────────────────────────
    [
        'key' => 'payment',
        'name' => 'Pembayaran',
        'info' => 'Metode pembayaran, gateway, timeout, dan kebijakan gagal bayar.',
        'sort' => 4,
    ],
    [
        'key' => 'payment.methods',
        'name' => 'Metode Pembayaran',
        'info' => 'Aktifkan/nonaktifkan metode pembayaran yang tampil di checkout.',
        'sort' => 1,
        'fields' => [
            ['name' => 'payment_bank_transfer_enabled', 'title' => 'Transfer Bank', 'type' => 'boolean', 'default' => '1'],
            ['name' => 'payment_qris_enabled', 'title' => 'QRIS (Manual)', 'type' => 'boolean', 'default' => '0'],
            ['name' => 'payment_midtrans_enabled', 'title' => 'Midtrans', 'type' => 'boolean', 'default' => '0'],
            ['name' => 'payment_doku_enabled', 'title' => 'DOKU Checkout', 'type' => 'boolean', 'default' => '0'],
            ['name' => 'payment_cod_enabled', 'title' => 'Bayar di Tempat (COD) — Segera Hadir', 'type' => 'boolean', 'default' => '0'],
        ],
    ],
    [
        'key' => 'payment.cod',
        'name' => 'COD',
        'info' => 'Fitur COD sedang dalam pengembangan. Di checkout ditampilkan sebagai "Segera Hadir" dan belum bisa dipilih. Aktifkan toggle di atas setelah flow kurir & konfirmasi pembayaran siap.',
        'sort' => 2,
        'fields' => [
            ['name' => 'cod_instructions', 'title' => 'Instruksi COD', 'type' => 'textarea', 'default' => 'Bayar tunai saat kurir mengantar pesanan. Pastikan nominal sesuai total pesanan.', 'validation' => 'nullable|string|max:1000'],
        ],
    ],
    [
        'key' => 'payment.qris',
        'name' => 'QRIS',
        'info' => 'Upload gambar QRIS statis untuk pembayaran manual.',
        'sort' => 3,
        'fields' => [
            ['name' => 'qris_image', 'title' => 'Gambar QRIS', 'type' => 'image', 'disk' => 'public', 'path' => 'payments', 'validation' => 'nullable|image|mimes:png,jpg,jpeg,webp|max:2048'],
            ['name' => 'qris_merchant_name', 'title' => 'Nama Merchant', 'type' => 'text', 'validation' => 'nullable|string|max:255'],
            ['name' => 'qris_instructions', 'title' => 'Instruksi Pembayaran', 'type' => 'textarea', 'default' => 'Scan QRIS di bawah, bayar sesuai nominal, lalu konfirmasi pembayaran.', 'validation' => 'nullable|string|max:1000'],
        ],
    ],
    [
        'key' => 'payment.banks',
        'name' => 'Rekening Transfer',
        'info' => 'Kelola rekening bank untuk transfer manual.',
        'sort' => 4,
        'type' => 'link',
        'href' => '/admin/payment-banks',
    ],
    [
        'key' => 'payment.midtrans',
        'name' => 'Midtrans',
        'info' => 'Konfigurasi payment gateway Midtrans. URL webhook dan callback tampil di bawah setelah membuka section ini.',
        'sort' => 5,
        'fields' => [
            ['name' => 'midtrans_active', 'title' => 'Aktifkan Midtrans', 'type' => 'boolean', 'default' => '0'],
            ['name' => 'midtrans_merchant_id', 'title' => 'Merchant ID', 'type' => 'text', 'validation' => 'nullable|string|max:100'],
            ['name' => 'midtrans_client_key', 'title' => 'Client Key', 'type' => 'text', 'validation' => 'nullable|string|max:255'],
            ['name' => 'midtrans_server_key', 'title' => 'Server Key', 'type' => 'password', 'validation' => 'nullable|string|max:255'],
            ['name' => 'midtrans_is_production', 'title' => 'Mode Production', 'type' => 'boolean', 'default' => '0'],
        ],
    ],
    [
        'key' => 'payment.doku',
        'name' => 'DOKU',
        'info' => 'Konfigurasi DOKU Checkout. URL webhook dan callback tampil di bawah setelah membuka section ini.',
        'sort' => 6,
        'fields' => [
            ['name' => 'doku_client_id', 'title' => 'Client ID', 'type' => 'text', 'validation' => 'nullable|string|max:255'],
            ['name' => 'doku_secret_key', 'title' => 'Secret Key', 'type' => 'password', 'validation' => 'nullable|string|max:255'],
            ['name' => 'doku_is_production', 'title' => 'Mode Production', 'type' => 'boolean', 'default' => '0'],
        ],
    ],
    [
        'key' => 'payment.timeout',
        'name' => 'Batas Waktu Pembayaran',
        'info' => 'Timeout dan auto-batal pesanan belum bayar.',
        'sort' => 7,
        'fields' => [
            ['name' => 'payment_timeout_hours', 'title' => 'Batas Waktu (jam)', 'type' => 'number', 'default' => '24', 'validation' => 'nullable|integer|min:1|max:168'],
            ['name' => 'auto_cancel_unpaid_orders', 'title' => 'Auto-batal Pesanan Expired', 'type' => 'boolean', 'default' => '1'],
            ['name' => 'send_email_on_payment_expired', 'title' => 'Email Saat Pembayaran Expired', 'type' => 'boolean', 'default' => '1'],
        ],
    ],
    [
        'key' => 'payment.failure',
        'name' => 'Pembayaran Gagal & Double',
        'info' => 'Handler kegagalan pembayaran dan transaksi duplikat.',
        'sort' => 8,
        'fields' => [
            ['name' => 'auto_cancel_on_payment_fail', 'title' => 'Auto-batal Saat Pembayaran Gagal', 'type' => 'boolean', 'default' => '1'],
            [
                'name' => 'payment_fail_action',
                'title' => 'Aksi Saat Pembayaran Gagal',
                'type' => 'select',
                'default' => 'cancel_order',
                'options' => [
                    ['title' => 'Batalkan Pesanan', 'value' => 'cancel_order'],
                    ['title' => 'Tetap Pending', 'value' => 'keep_pending'],
                    ['title' => 'Tandai Gagal (failed)', 'value' => 'mark_failed'],
                ],
            ],
            ['name' => 'log_duplicate_webhooks', 'title' => 'Log Webhook Duplikat', 'type' => 'boolean', 'default' => '1'],
            ['name' => 'reject_webhook_amount_mismatch', 'title' => 'Tolak Webhook Nominal Tidak Cocok', 'type' => 'boolean', 'default' => '1'],
            ['name' => 'max_payment_confirmation_attempts', 'title' => 'Max Konfirmasi Transfer', 'type' => 'number', 'default' => '3', 'validation' => 'nullable|integer|min:1|max:10'],
        ],
    ],

    // ── Konten Situs ──────────────────────────────────────────────────────
    [
        'key' => 'content',
        'name' => 'Konten Situs',
        'info' => 'Halaman utama dan konten storefront.',
        'sort' => 5,
    ],
    [
        'key' => 'content.homepage',
        'name' => 'Halaman Utama',
        'info' => 'Builder layout homepage dan slider.',
        'sort' => 1,
        'type' => 'link',
        'href' => '/admin/homepage',
    ],
];
